DROP TABLE IF EXISTS item_pedido;
DROP TABLE IF EXISTS pedido;
DROP TABLE IF EXISTS item_contrato;
DROP TABLE IF EXISTS contrato;
DROP TABLE IF EXISTS proposta;
DROP TABLE IF EXISTS fornecedor;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS licitacao;
DROP TABLE IF EXISTS orgao;

CREATE TABLE orgao (
    id_orgao INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome_orgao VARCHAR(200) NOT NULL,

    CONSTRAINT pk_orgao PRIMARY KEY (id_orgao)
);

CREATE TABLE licitacao (
    id_licitacao INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_orgao INTEGER NOT NULL,
    numero VARCHAR(30) NOT NULL,
    objeto TEXT NOT NULL,
    exercicio INTEGER NOT NULL,
    modalidade VARCHAR(30) NOT NULL,
    situacao varchar(30) not null default 'ABERTA',
    data_inicio DATE NOT NULL,
    data_encerramento date,

    constraint pk_licitacao primary key (id_licitacao),
    
    constraint fk_licitacao_orgao foreign key (id_orgao) references orgao(id_orgao) ON DELETE RESTRICT,

    constraint uq_licitacao unique (id_orgao, numero, exercicio),

    constraint ck_licitacao_exercicio check (exercicio >= 2000 and exercicio <= 2100),

    constraint ck_licitacao_situacao check (situacao in ('ABERTA', 'EM ANDAMENTO', 'HOMOLOGADA', 'CANCELADA')),

    constraint ck_licitacao_data_encerramento check (data_encerramento is null or data_encerramento >= data_inicio )
);

create table item(
    id_item integer generated by default as identity,
    id_licitacao integer not null,
    descricao text not null,
    quantidade_licitada numeric(14,3) not null,
    unidade_medida varchar(20) not null,
    valor_referencia numeric(14,2) not null,

    constraint pk_item primary key (id_item),
    constraint fk_item_licitacao foreign key (id_licitacao) references licitacao(id_licitacao) on delete restrict,
    constraint ck_item_quantidade check (quantidade_licitada > 0),
    constraint ck_item_valor_referencia check (valor_referencia >= 0)

);
    
create table fornecedor(
    id_fornecedor integer generated by default as identity,
    nome_fornecedor varchar(200) not null,
    cnpj varchar(14) not null,
    rua varchar(200) not null,
    cidade varchar(100) not null,

    constraint pk_fornecedor primary key (id_fornecedor),
    constraint uq_fornecedor_cnpj unique (cnpj),
    constraint ck_fornecedor_cnpj check ( cnpj ~ '^[0-9]{14}$')
);

CREATE table proposta(
    id_item integer not null, 
    id_fornecedor integer not null,
    preco_unitario numeric(14,2) not null,
    quantidade_ofertada numeric(14,3) not null,
    situacao varchar(30) not null default 'APRESENTADA',

    constraint pk_proposta primary key (id_item, id_fornecedor),
    constraint fk_proposta_item foreign key (id_item) references item(id_item) on delete restrict,
    constraint fk_proposta_fornecedor foreign key (id_fornecedor) references fornecedor(id_fornecedor) on delete restrict,
    constraint ck_proposta_preco check (preco_unitario >= 0),
    constraint ck_proposta_quantidade check (quantidade_ofertada > 0), 
    constraint ck_proposta_situacao check (situacao in ('APRESENTADA', 'CLASSIFICADA', 'DESCLASSIFICADA', 'VENCEDORA'))

);
CREATE UNIQUE INDEX uq_proposta_vencedora_item
    ON proposta (id_item)
    WHERE situacao = 'VENCEDORA';

create table contrato(
    id_contrato integer generated by default as identity,
    id_licitacao integer not null,
    id_fornecedor integer not null,
    numero varchar(30) not null,
    data_inicio date not null,
    data_termino date not null,
    situacao varchar(20) not null default 'ATIVO',

    constraint pk_contrato primary key (id_contrato),
    constraint fk_contrato_licitacao foreign key (id_licitacao) references licitacao (id_licitacao) on delete restrict,
    constraint fk_contrato_fornecedor foreign key (id_fornecedor) references fornecedor (id_fornecedor ) on delete restrict,
    constraint uq_contrato unique (id_licitacao, numero),
    constraint ck_contrato_periodo check (data_termino >= data_inicio),
    constraint ck_contrato_situacao check (situacao in ('ATIVO', 'ENCERRADO', 'CANCELADO'))
);

create table item_contrato(
    id_item_contrato integer generated by default as identity,
    id_contrato integer not null,
    id_item integer not null,
    quantidade_contratada numeric(14,3) not null,
    valor_unitario_contratado numeric(14,2) not null,

    constraint pk_item_contrato primary key (id_item_contrato),
    constraint fk_item_contrato_contrato foreign key (id_contrato) references contrato(id_contrato) on delete restrict,
    constraint fk_item_contrato_item foreign key (id_item) references item(id_item) on delete restrict,
    constraint uq_item_contrato unique (id_item),
    CONSTRAINT ck_item_contrato_quantidade CHECK (quantidade_contratada > 0),
    CONSTRAINT ck_item_contrato_valor CHECK (valor_unitario_contratado >= 0)
);
CREATE TABLE pedido (
    id_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_contrato INTEGER NOT NULL,
    solicitante VARCHAR(150) NOT NULL,
    data_pedido DATE NOT NULL DEFAULT CURRENT_DATE,

    CONSTRAINT pk_pedido
        PRIMARY KEY (id_pedido),

    CONSTRAINT fk_pedido_contrato
        FOREIGN KEY (id_contrato)
        REFERENCES contrato (id_contrato)
        ON DELETE RESTRICT
);

CREATE TABLE item_pedido (
    id_pedido INTEGER NOT NULL,
    id_item_contrato INTEGER NOT NULL,
    quantidade_pedida NUMERIC(14,3) NOT NULL,

    CONSTRAINT pk_item_pedido
        PRIMARY KEY (id_pedido, id_item_contrato),

    CONSTRAINT fk_item_pedido_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES pedido (id_pedido)
        ON DELETE RESTRICT,

    CONSTRAINT fk_item_pedido_item_contrato
        FOREIGN KEY (id_item_contrato)
        REFERENCES item_contrato (id_item_contrato)
        ON DELETE RESTRICT,

    CONSTRAINT ck_item_pedido_quantidade
        CHECK (quantidade_pedida > 0)
);
create or replace function fn_validar_licitacao_contrato() returns trigger language plpgsql as $$
declare 
    v_situacao varchar(30);
begin
    select situacao into v_situacao from licitacao where id_licitacao = new.id_licitacao;
    if v_situacao is null then
        raise exception 'Licitacao % não encontrada', new.id_licitacao;
    end if;
    if v_situacao <> 'HOMOLOGADA' then
        raise exception 'A licitacao % deve estar HOMOLOGADA para gerar contrato', new.id_licitacao;
    end if;
    return new;
end;
$$;

create trigger trg_validar_licitacao_contrato
before insert or update of id_licitacao on contrato
for each row execute function fn_validar_licitacao_contrato();

CREATE OR REPLACE FUNCTION fn_validar_item_contrato()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_licitacao_item INTEGER;
    v_licitacao_contrato INTEGER;
    v_fornecedor_contrato INTEGER;
    v_quantidade_licitada NUMERIC(14,3);
BEGIN
    SELECT id_licitacao, quantidade_licitada
      INTO v_licitacao_item, v_quantidade_licitada
      FROM item
     WHERE id_item = NEW.id_item;

    IF v_licitacao_item IS NULL THEN
        RAISE EXCEPTION
            'Item % nao encontrado',
            NEW.id_item;
    END IF;

    SELECT id_licitacao, id_fornecedor
      INTO v_licitacao_contrato, v_fornecedor_contrato
      FROM contrato
     WHERE id_contrato = NEW.id_contrato;

    IF v_licitacao_contrato IS NULL THEN
        RAISE EXCEPTION
            'Contrato % nao encontrado',
            NEW.id_contrato;
    END IF;

    IF v_licitacao_item <> v_licitacao_contrato THEN
        RAISE EXCEPTION
            'O item % nao pertence a licitacao do contrato %',
            NEW.id_item,
            NEW.id_contrato;
    END IF;

    IF NEW.quantidade_contratada > v_quantidade_licitada THEN
        RAISE EXCEPTION
            'Quantidade contratada % supera a quantidade licitada %',
            NEW.quantidade_contratada,
            v_quantidade_licitada;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM proposta
         WHERE id_item = NEW.id_item
           AND id_fornecedor = v_fornecedor_contrato
           AND situacao = 'VENCEDORA'
    ) THEN
        RAISE EXCEPTION
            'O fornecedor do contrato nao possui proposta vencedora para o item %',
            NEW.id_item;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_item_contrato
BEFORE INSERT OR UPDATE OF
    id_contrato,
    id_item,
    quantidade_contratada
ON item_contrato
FOR EACH ROW
EXECUTE FUNCTION fn_validar_item_contrato();

CREATE OR REPLACE FUNCTION fn_validar_pedido()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_data_inicio DATE;
    v_data_termino DATE;
    v_situacao VARCHAR(20);
BEGIN
    SELECT data_inicio, data_termino, situacao
      INTO v_data_inicio, v_data_termino, v_situacao
      FROM contrato
     WHERE id_contrato = NEW.id_contrato;

    IF v_situacao IS NULL THEN
        RAISE EXCEPTION
            'Contrato % nao encontrado',
            NEW.id_contrato;
    END IF;

    IF v_situacao <> 'ATIVO' THEN
        RAISE EXCEPTION
            'O contrato % deve estar ATIVO para receber pedidos',
            NEW.id_contrato;
    END IF;

    IF NEW.data_pedido < v_data_inicio
       OR NEW.data_pedido > v_data_termino THEN
        RAISE EXCEPTION
            'Data do pedido % fora da vigencia do contrato: % a %',
            NEW.data_pedido,
            v_data_inicio,
            v_data_termino;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_pedido
BEFORE INSERT OR UPDATE OF id_contrato, data_pedido
ON pedido
FOR EACH ROW
EXECUTE FUNCTION fn_validar_pedido();

CREATE OR REPLACE FUNCTION fn_validar_item_pedido()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_contrato_pedido INTEGER;
    v_contrato_item INTEGER;
    v_quantidade_contratada NUMERIC(14,3);
    v_quantidade_ja_pedida NUMERIC(14,3);
    v_saldo NUMERIC(14,3);
BEGIN
    SELECT id_contrato, quantidade_contratada
      INTO v_contrato_item, v_quantidade_contratada
      FROM item_contrato
     WHERE id_item_contrato = NEW.id_item_contrato
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Item contratado % nao encontrado',
            NEW.id_item_contrato;
    END IF;

    SELECT id_contrato
      INTO v_contrato_pedido
      FROM pedido
     WHERE id_pedido = NEW.id_pedido;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Pedido % nao encontrado',
            NEW.id_pedido;
    END IF;

    IF v_contrato_pedido <> v_contrato_item THEN
        RAISE EXCEPTION
            'O item contratado % nao pertence ao contrato do pedido %',
            NEW.id_item_contrato,
            NEW.id_pedido;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        SELECT COALESCE(SUM(quantidade_pedida), 0)
          INTO v_quantidade_ja_pedida
          FROM item_pedido
         WHERE id_item_contrato = NEW.id_item_contrato
           AND NOT (
               id_pedido = OLD.id_pedido
               AND id_item_contrato = OLD.id_item_contrato
           );
    ELSE
        SELECT COALESCE(SUM(quantidade_pedida), 0)
          INTO v_quantidade_ja_pedida
          FROM item_pedido
         WHERE id_item_contrato = NEW.id_item_contrato;
    END IF;

    v_saldo :=
        v_quantidade_contratada - v_quantidade_ja_pedida;

    IF NEW.quantidade_pedida > v_saldo THEN
        RAISE EXCEPTION
            'Quantidade pedida % supera o saldo disponivel %',
            NEW.quantidade_pedida,
            v_saldo;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_item_pedido
BEFORE INSERT OR UPDATE OF
    id_pedido,
    id_item_contrato,
    quantidade_pedida
ON item_pedido
FOR EACH ROW
EXECUTE FUNCTION fn_validar_item_pedido();

CREATE OR REPLACE FUNCTION fn_validar_quantidade_proposta()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_quantidade_licitada NUMERIC(14,3);
BEGIN
    SELECT quantidade_licitada
      INTO v_quantidade_licitada
      FROM item
     WHERE id_item = NEW.id_item;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Item % nao encontrado',
            NEW.id_item;
    END IF;

    IF NEW.quantidade_ofertada > v_quantidade_licitada THEN
        RAISE EXCEPTION
            'Quantidade ofertada % supera a quantidade licitada %',
            NEW.quantidade_ofertada,
            v_quantidade_licitada;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_quantidade_proposta
BEFORE INSERT OR UPDATE OF id_item, quantidade_ofertada
ON proposta
FOR EACH ROW
EXECUTE FUNCTION fn_validar_quantidade_proposta();

CREATE INDEX idx_item_licitacao
    ON item (id_licitacao);

CREATE INDEX idx_proposta_fornecedor
    ON proposta (id_fornecedor);

CREATE INDEX idx_contrato_fornecedor
    ON contrato (id_fornecedor);

CREATE INDEX idx_item_contrato_contrato
    ON item_contrato (id_contrato);

CREATE INDEX idx_pedido_contrato
    ON pedido (id_contrato);

CREATE INDEX idx_item_pedido_item_contrato
    ON item_pedido (id_item_contrato);

